version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db-dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1qaz2wsx'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - /storage/data/mysql:/var/lib/mysql

# volumes:
#    dbdata:
#       driver: local
#       driver_opts:
#          o: bind
#          type: none
#          device: /Users/chenjiawei/storage/data/mysql